package mx.com.server.cae.models;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

@Document(collection = "users") // Maps Entity class objects to JSON formatted Documents
public class User implements Serializable {

    private static final long serialVersionUID = -7788619177798333712L;

    @MongoId(FieldType.OBJECT_ID) // making this variable as ID, will be auto-generated by MongoDB
    private String id;

    @Field("username")
    private String username;

    @Field("email")
    private String email;

    @Field("password")
    private String password;

    @Field("enabled")
    private boolean enabled;

    @Field("created_at")
    private Date createdAt;

    @Field("last_changed_at")
    private Date lastChangedAt;

    @Field("provider")
    private String provider;

    private List<Role> roles;

    @Field("last_accessed_")
    private Date lastAccessedAt;

    @Field("last_password_changed_at")
    private Date lastPasswordChangedAt;

    public User() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getLastChangedAt() {
        return lastChangedAt;
    }

    public void setLastChangedAt(Date lastChangedAt) {
        this.lastChangedAt = lastChangedAt;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    public Date getLastAccessedAt() {
        return lastAccessedAt;
    }

    public void setLastAccessedAt(Date lastAccessedAt) {
        this.lastAccessedAt = lastAccessedAt;
    }

    public Date getLastPasswordChangedAt() {
        return lastPasswordChangedAt;
    }

    public void setLastPasswordChangedAt(Date lastPasswordChangedAt) {
        this.lastPasswordChangedAt = lastPasswordChangedAt;
    }

    @Override
    public String toString() {
        return "User{" + "id=" + id + ", username=" + username + ", email=" + email + ", password=" + password + ", enabled=" + enabled + ", createdAt=" + createdAt + ", lastChangedAt=" + lastChangedAt + ", provider=" + provider + ", roles=" + roles + ", lastAccessedAt=" + lastAccessedAt + ", lastPasswordChangedAt=" + lastPasswordChangedAt + '}';
    }

}
